name: Обновление конфигов Miltary VPN

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    paths:
      - 'pp2.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 pyyaml maxminddb
      - name: Восстановление кэша MaxMind DB
        uses: actions/cache@v3
        id: cache-mmdb
        with:
          path: temp/GeoLite2-Country.mmdb
          key: mmdb-${{ runner.os }}-latest
      - name: Создание папки temp (если нет)
        run: mkdir -p temp
      - name: Запуск скрипта
        run: python pp2.py
        env:
          PYTHONUNBUFFERED: 1
      - name: Коммит и пуш изменений
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автоматическое обновление конфигов Miltary VPN"
          file_pattern: |
            MiltaryVPN.txt
            MiltaryVPN_Happ.txt
            MiltaryVPN.yaml
            log.csv
            temp/GeoLite2-Country.mmdb
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
